package ren.com.cn.dao.mapper.mbg;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ren.com.cn.domain.entity.TCrmComments;
import ren.com.cn.domain.entity.TCrmCommentsExample;

public interface MBGTCrmCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int countByExample(TCrmCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int deleteByExample(TCrmCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int insert(TCrmComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int insertSelective(TCrmComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    List<TCrmComments> selectByExample(TCrmCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    TCrmComments selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TCrmComments record, @Param("example") TCrmCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TCrmComments record, @Param("example") TCrmCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCrmComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_crm_comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCrmComments record);
}