# 端口，暂无作用server:
server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1101
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.qq.com
    username: 820941512@qq.com
    password: veggixwavigrbbfa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  mvc:
    view:
        prefix: /templates/
        suffix: .html

# redis配置
redis:
    minIdle: 100
    maxIdle: 300
    maxTotal: 1500
    #超时时间为3秒
    maxWaitMillis: 8000
    expireSeconds: 3
    clusterNodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005


kafka:
   brokerList: 127.0.0.1:9093,127.0.0.1:9094
   serializerClass: kafka.serializer.StringEncoder
   keySerializerClass: kafka.serializer.StringEncoder
   partitionerClass: kafka.producer.DefaultPartitioner
   requestRequiredAcks: 1
   connectTimeoutMs: 3000
   socketTimeoutMs: 1000
   consumer:
            zookeeperConnect: 127.0.0.1:2181
email:
  fromAddr: 820941512@qq.com



