# 端口，暂无作用server:
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1101
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.qq.com
    username: 820941512@qq.com
    password: veggixwavigrbbfa1
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  mvc:
    view:
        prefix: /templates/
        suffix: .html

# redis配置
redis:
    host: 10.101.91.246
    port: 8035
    minIdle: 100
    maxIdle: 300
    maxTotal: 1500

    #超时时间为3秒
    timeout: 3000
    maxWaitMillis: 8000
    expireSeconds: 3
    clusterNodes: 10.101.91.246:8035


kafka:
   brokerList: 127.0.0.1:9093,127.0.0.1:9094,127.0.0.1:9095
   serializerClass: kafka.serializer.StringEncoder
   keySerializerClass: kafka.serializer.StringEncoder
   partitionerClass: kafka.producer.DefaultPartitioner
   requestRequiredAcks: 1
   connectTimeoutMs: 3000
   socketTimeoutMs: 1000
   consumer:
            zookeeperConnect: 127.0.0.1:2181
email:
  fromAddr: 820941512@qq.com



